export const FailCode = {
  NONE: 0,
  UNKNOWN_ERROR: 1,
  INVALID_REQUEST: 2,
  AUTHENTICATION_FAILED: 3,
  REGISTER_FAILED: 4,
  CREATE_ROOM_FAILED: 5,
  JOIN_ROOM_FAILED: 6,
  LEAVE_ROOM_FAILED: 7,
};
